inserted cluster and partition fields
stellar/stellar-etl-airflow pull request #123
Opened 2023-03-17 12:23 UTC by cayod

This PR is related to issue #341, after a review of the tables that will not go to the dbt flow, the tables that have changed history_assets, history_ledgers, history_operations, history_trades, history_transactions, enriched_history_operation, enriched_meaningful_history_operation, account_signers, account, claimable_balances, liquidity_pools, offers, trust_lines.
The clusters were changed and the partitions of the tables that were not partitioned were inserted.

2023-03-17 18:39 UTC, sydneynotthecity approved these changes
Updates look good. As a note, the public dataset `crypto-stellar.crypto_stellar_2` is clustered by the original specification. The clustering for these tables will need to be updated when this change is deployed.

2023-03-22 14:31 UTC, lucaszanotelli commented
@cayod you should also change the `dags/ddls/create_partitioned_tables.sh` file to reflect these changes.

2023-03-22 14:36 UTC, lucaszanotelli requested changes
There's a `_te` suffix in EHO and EMHO tables on variables files that should be removed.

2023-03-22 21:16 UTC, lucaszanotelli approved these changes
LGTM

2023-03-27 13:59 UTC, merged